---
services:
  dokuwiki:
    image: vndmtrx/dokuwiki:latest
    container_name: dokuwiki
    ports:
      - "8080:80"
    volumes:
      - dokuwiki_data:/dokuwiki
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: www-data
    environment:
      - TZ=America/Sao_Paulo
      - DOKUWIKI_TITLE=DokuWiki Docker Image
      - DOKUWIKI_LANG=en
      - DOKUWIKI_LICENSE=gnufdl
      - DOKUWIKI_TAGLINE=A secure, rootless Docker image for DokuWiki with persistent storage support
      - DOKUWIKI_BASEURL=http://localhost:8080
      - DOKUWIKI_DATEFORMAT=%d/%m/%Y %H:%M
      - DOKUWIKI_USEREWRITE=1
      - DOKUWIKI_USEACL=1
      - DOKUWIKI_SUPERUSER=admin
      - DOKUWIKI_SUPERPASS=very_secure_password
      - DOKUWIKI_FULLNAME=Administrator
      - DOKUWIKI_EMAIL=admin@example.com
      - DOKUWIKI_DISABLEACTIONS=register
      - DOKUWIKI_AUTHTYPE=authplain
      - DOKUWIKI_DEFAULTGROUP=user
      - DOKUWIKI_ACL_POLICY=public  # Can be: open, public, or closed (default: open)
      #- DOKUWIKI_FORCE_CONF=1

volumes:
  dokuwiki_data:
    external: true
    name: dokuwiki_data