#!/usr/bin/env bash

set -uo pipefail

CONF_DIR="/dokuwiki/conf"
LOCAL_FILE="$CONF_DIR/local.php"
ACL_FILE="$CONF_DIR/acl.auth.php"
USERS_FILE="$CONF_DIR/users.auth.php"
FORCE_CONF="${DOKUWIKI_FORCE_CONF:-0}"

# Check if configuration files exist
if [ -f "$LOCAL_FILE" ] && [ -f "$ACL_FILE" ] && [ -f "$USERS_FILE" ] && [ "$FORCE_CONF" != "1" ]; then
    exec apache2-foreground
fi

create_local_file() {
    local file="$1"
    {
        echo "<?php"
        echo "// DokuWiki configuration file"
        echo "// Generated by initialization script"
        echo
    } > "$file"
}

update_config() {
    local key="$1"
    local value="$2"
    
    [ ! -f "$LOCAL_FILE" ] && create_local_file "$LOCAL_FILE"
    
    if grep -q "^\$conf\['${key}'\]" "$LOCAL_FILE"; then
        sed -i "s|\$conf\['${key}'\] *= *.*|\$conf['${key}'] = ${value};|" "$LOCAL_FILE"
    else
        echo "\$conf['${key}'] = ${value};" >> "$LOCAL_FILE"
    fi
}

setup_acl_policy() {
    local policy="${DOKUWIKI_ACL_POLICY:-open}"
    [ -f "$ACL_FILE" ] && return 0

    case "$policy" in
        open)    echo "*               @ALL          16" > "$ACL_FILE" ;;
        public)  { 
            echo "*               @ALL          1"
            echo "*               @user         8"
        } > "$ACL_FILE" ;;
        closed)  echo "*               @user         15" > "$ACL_FILE" ;;
        *)       echo "*               @ALL          16" > "$ACL_FILE" ;;
    esac
}

process_basic_configs() {
    local config_provided=false
    local configs=(
        "DOKUWIKI_TITLE|title"
        "DOKUWIKI_LANG|lang"
        "DOKUWIKI_LICENSE|license"
        "DOKUWIKI_TAGLINE|tagline"
        "DOKUWIKI_BASEURL|baseurl"
        "DOKUWIKI_USEACL|useacl"
        "DOKUWIKI_DISABLEACTIONS|disableactions"
        "DOKUWIKI_AUTHTYPE|authtype"
        "DOKUWIKI_DEFAULTGROUP|defaultgroup"
        "DOKUWIKI_DATEFORMAT|dformat"
        "DOKUWIKI_USEREWRITE|userewrite"
    )

    for config in "${configs[@]}"; do
        local env_var=${config%|*}
        local key=${config#*|}
        [ -n "${!env_var:-}" ] && {
            update_config "$key" "'${!env_var}'"
            config_provided=true
        }
    done
    echo "$config_provided"
}

setup_superadmin() {
    [ -z "${DOKUWIKI_SUPERUSER:-}" ] || [ -z "${DOKUWIKI_SUPERPASS:-}" ] || 
    [ -z "${DOKUWIKI_FULLNAME:-}" ] || [ -z "${DOKUWIKI_EMAIL:-}" ] && return 1
    
    grep -q "^\$conf\['superuser'\]" "$LOCAL_FILE" || update_config "superuser" "'@admin'"
    
    local hashed_password=$(php -r "echo password_hash('${DOKUWIKI_SUPERPASS}', PASSWORD_BCRYPT);")
    local user_line="${DOKUWIKI_SUPERUSER}:${hashed_password}:${DOKUWIKI_FULLNAME}:${DOKUWIKI_EMAIL}:admin,user"
    
    if grep -q "^${DOKUWIKI_SUPERUSER}:" "$USERS_FILE" 2>/dev/null; then
        sed -i "s|^${DOKUWIKI_SUPERUSER}:.*|$user_line|" "$USERS_FILE"
    else
        echo "$user_line" >> "$USERS_FILE"
    fi
    return 0
}

remove_install() {
    local config_provided="$1"
    local install_file="/var/www/html/install.php"
    [ "$config_provided" = true ] && [ -f "$install_file" ] && rm "$install_file"
}

config_provided=$(process_basic_configs)
setup_acl_policy
setup_superadmin && config_provided=true
remove_install "$config_provided"

exec apache2-foreground